name: Update YouTube Videos
on:
  workflow_dispatch:

jobs:
  dev
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - uses: actions/checkout@v2
      - name: run a script
        run: | 
           echo " I am running in dev env"
          
